message: '&4Hello %version'
help_wolf_1_0: 'this is WereWolf help!'
help_wolf_1_1: '/wolf message'
help_wolf_1_2: 'this is demo command'
help_wolf_1_3:
help_wolf_1_4:
help_wolf_1_5:
help_wolf_1_6:
help_wolf_1_7:
help_wolf_2_0:
help_wolf_2_1:
help_wolf_2_2:
help_wolf_2_3:
help_wolf_2_4:
help_wolf_2_5:
help_wolf_2_6:
help_wolf_2_7:
rule_wolf_1_0:
rule_wolf_1_1:
rule_wolf_1_2:
rule_wolf_1_3:
rule_wolf_1_4:
rule_wolf_1_5:
rule_wolf_1_6:
rule_wolf_1_7:
